language: go
go:
  - 1.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq libgl1-mesa-dev libgles2-mesa-dev xorg-dev
install:
  - go get golang.org/x/tools/cmd/vet
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d ./)
  - go tool vet -composites=false ./
  - go test -v -race ./...
after_success:
  - bash -c "$(curl -fsSL http://bitly.com/gorelease)" gorelease
